server:
  port: 8081

spring:
  application:
    name: payment-platform
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

payments:
  security:
    client-id: ${PAYMENTS_CLIENT_ID:bancobilhetes-app}
    client-secret: ${PAYMENTS_CLIENT_SECRET:bancobilhetes-secret}

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:payments;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://payment-db:5432/payments
    username: ${DB_USER:payments}
    password: ${DB_PASSWORD:payments}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
